services:
  - type: web
    name: vika-neiro-bot
    runtime: python
    region: frankfurt
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg && pip install -r requirements.txt
    startCommand: python aiogram_bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: 8249255843:AAE0fPLcPpmJqyWGK70xJ06mOacatNVEUgc
      - key: CLIENT_ID
        value: 019c9dd5-08ad-714c-8358-5945e8c15fee
      - key: CLIENT_SECRET
        value: 90a0e997-4015-458f-907a-d59f5d9e68a7